# INHERITANCE AND TYPES

In [174]:
#SINGLE INHERITANCE

In [175]:
# Python program
 
# Base class
class Object:
    def func1(self):
        print("Object name:CAR")
 
# Derived class
 
 
class Brand(Object):
    def func2(self):
        print("Brand:BMW")
 
 
# Driver's code
object = Brand()
object.func1()
object.func2()

Object name:CAR
Brand:BMW


In [8]:
# MULTIPLE INHERITANCE

In [11]:
class Mother:
    mothername = ""
 
    def mother(self):
        print(self.mothername)
 
# Base class2
 
 
class Father:
    fathername = ""
 
    def father(self):
        print(self.fathername)
 
# Derived class
 
 
class Daughter(Mother, Father):
    def parents(self):
        print("Father :", self.fathername)
        print("Mother :", self.mothername)
 
 
# Driver's code
s1 = Daughter()
s1.fathername = "RAM"
s1.mothername = "YOSHI"
s1.parents()

Father : RAM
Mother : YOSHI


In [18]:
# HIERARCHIAL INHERITANCE

In [59]:
class student:
    def func1(self):
        marks=(98+78+76+46+67)/5
        print('marks',marks)
#Derived Class
class grade(student):
    def func2(self):
            print('A Grade')

object1=grade()
object1.func1()
object1.func2()


marks 73.0
A Grade


In [55]:
#Hybrid Inheritance

In [73]:
class Car:
    def func1(self):
        print("DISPLAY Car Brands!!")
 
 
class c1(Car):
    def func2(self):
        print("1.AUDI\n2.BMW\n3.BENZ\n")
 
 
class c2(Car):
    def func3(self):
        print("Expensive: Roles ROYCE")
 
class c3(c1,c2):
    def func4(self):
        print('car')
 
# Driver's code
object = c3()
object.func1()
object.func2()
object.func3()

DISPLAY Car Brands!!
1.AUDI
2.BMW
3.BENZ

Expensive: Roles ROYCE


In [74]:
#Multilevel Inheritance

In [2]:
 
class Grandfather:
 
    def __init__(self, grandfathername):
        self.grandfathername = grandfathername
 
# Intermediate class
 
 
class Father(Grandfather):
    def __init__(self, fathername, grandfathername):
        self.fathername = fathername
 
        # invoking constructor of Grandfather class
        Grandfather.__init__(self, grandfathername)
 
# Derived class
 
 
class Son(Father):
    def __init__(self, sonname, fathername, grandfathername):
        self.sonname = sonname
 
        # invoking constructor of Father class
        Father.__init__(self, fathername, grandfathername)
 
    def print_name(self):
        print('Grandfather name :', self.grandfathername)
        print("Father name :", self.fathername)
        print("Son name :", self.sonname)
 
 
#  Driver code
s1 = Son('prince', 'Gopi', 'Vaithi')
s1.print_name()

Grandfather name : Vaithi
Father name : Gopi
Son name : prince


# EXCEPTION HANDLE

In [1]:
#1.
Rate = { 'bottle' : 5, 'chair' : 1200, 'pen' : 50}
item = input('Enter the item: ')
try:
   print(f'The rate of {item} is {Rate[item]}')
except KeyError:
    print(f'The price of {item} is not found')

Enter the item: bottle
The rate of bottle is 5


In [7]:
#2.
try:  
    a = 5
    b = 5
    assert a != b
except AssertionError:  
        if a==b:
            print("TRUE") 
print ("Success, no error!")

TRUE
Success, no error!


In [4]:
#3.
class Attributes(object):
    num = 5
    print(num)
try:
    object = Attributes()
    print (object.attribute)
except AttributeError:
    print ("Attribute Exception")

5
Attribute Exception


In [3]:
#4.
try:
    a=int(input("enter:"))
    Type=a[1]
except ValueError:    #Two or more int elements given as inputs
    print("Error Handled!")



enter:12,4
Error Handled!


In [15]:
#5.
import numpy as np
try:
    a=[12,34,56,78,98]
    print(np.max(a))
except IndentationError:
    print(np.max(a))

98


In [1]:
#6.
def fun(a):
    if a < 4:
  
        # throws ZeroDivisionError for a = 3
        b = a/(a-3)
  
    # throws NameError if a >= 4
    print("Value of b = ", b)
      
try:
    fun(2)
    fun(5)
  
# note that braces () are necessary here for 
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")

Value of b =  -2.0
NameError Occurred and Handled


# Regular Experssion

In [31]:
#1.
# re.findall()
import pandas as pd
import numpy as np
import re
str1='Hello 12 rt 78. Cowboy 23'
pattern = '\d+'

result = re.findall(pattern,str1)
print(result)

['12', '78', '23']


In [53]:
#2.
#re.split()
string='twelve:12 Eighty nine:89 fourty:40'
pattern='\s+'

#maxsplit = 1
#split only at the first occurence

result  = re.split(pattern,string,1)
print(result)

['twelve:12', 'Eighty nine:89 fourty:40']


In [73]:
#3.
#re.sub()
s1='abc 12\ de 23 \n f45 6'
    # matches all whitespace characters
pattern='\s+'

#empty string
replace = '\t&&\t'     # && denotes white spaces

new = re.sub(pattern,replace,s1)
print(new)

abc	&&	12\	&&	de	&&	23	&&	f45	&&	6


In [86]:
#4.
#re.search()
s2='Python is Craze'
#check if python is beginning
match = re.search('\APython',s2)
m1=s2[0:6]

if match:
    print('Pattern found inside the string')
    print('Index:',m1)
else:
    print('Pattern not found!!')
    

Pattern found inside the string
Index: Python


# NUMPY

In [226]:
import numpy as np
#one-dim
l=np.random.randint(10,50,20)
l

array([46, 38, 23, 14, 18, 11, 31, 28, 39, 23, 30, 23, 35, 35, 47, 48, 20,
       26, 17, 37])

In [227]:
#Sum
np.sum(l)

589

In [228]:
#max
np.max(l)

48

In [229]:
#min
np.min(l)

11

In [230]:
#multi-Dim
M=np.random.randint(10,40,(3,4))
M

array([[15, 35, 35, 18],
       [15, 34, 14, 23],
       [17, 29, 22, 23]])

In [231]:
#sum
print(np.sum(M,axis=1))

print(np.sum(M,axis=0))

[103  86  91]
[47 98 71 64]


In [232]:
#max
print('Max',np.max(M,axis=1))
print('Min',np.min(M,axis=0))

Max [35 34 29]
Min [15 29 14 18]


In [233]:
#Prod
l1=np.random.randint(10,20,3)
print(l1)
prod=np.prod(l1)
prod

[15 16 17]


4080

In [234]:
#Mean
mean=np.mean(l1)
print(l1)
print(mean)

[15 16 17]
16.0


In [235]:
#std
l2=np.random.randint(10,20,3)
print(l2)
std=np.std(l2)
print(std)

[13 19 13]
2.8284271247461903


In [236]:
#any
a=[0,8,0]
np.any(a)          # it returns true if any value non-zero

True

In [237]:
#all
x=[2,4,6,0,8]
np.all(x)          # it returns false if any one value is zero

False

In [238]:
#Median
x=list((12,45,67,89,90))
print(x)
med=np.median(x)
print(med)

[12, 45, 67, 89, 90]
67.0


# Boolean and Masking

In [239]:
#Masking
import numpy.ma as ma
m = np.zeros(4)
m
x=np.array([0., 0., 0., 0.])
ma.make_mask(m)
False
ma.make_mask(m, shrink=False)
np.array([False, False, False, False])

array([False, False, False, False])

In [240]:
#Comparisons
# <
a=np.array([12,45,67,34,90,34])
print(a)
x=a<40
print('1.',x)

# >

print('\n2.',a>40)

# ==

print('\n3.',a==45)

# <=

print('\n4.',a<=40)

# >=

print('\n5.',a>=40)


# !=

print('\n6.',a!=67)

[12 45 67 34 90 34]
1. [ True False False  True False  True]

2. [False  True  True False  True False]

3. [False  True False False False False]

4. [ True False False  True False  True]

5. [False  True  True False  True False]

6. [ True  True False  True  True  True]


# BOOL

In [241]:
bool(42),bool(0)

(True, False)

In [242]:
bool(42 and 0)

False

In [243]:
bool(42 or 0)

True

# Bin

In [244]:
bin(55)

'0b110111'

In [245]:
bin(0)

'0b0'

In [246]:
bin(55 & 0)

'0b0'

In [247]:
bin(55 | 0)

'0b110111'

In [248]:
bin(55|2)

'0b110111'

 #                               '...THE PROGRAMS FINISED...'