# 11

In [7]:
def show_stars(n):
    for i in range(0,n):
        for j in range(0,i+1):
            print("*",end="")
        print("\r")
n=5
show_stars(n)

*
**
***
****
*****


# 12

In [1]:
def belong(word,n):
    print("Real String:", word)
    x=word[n:]
    return x

print("Removing Chars From String")
print(belong("Quantitative",5))
print(belong("Hurry",2))


Removing Chars From String
Real String: Quantitative
itative
Real String: Hurry
rry


# 13

In [13]:
def division(numbers):
    print("Given Numbers is:",numbers)
    print("Divisible of 5 in numbers")
    for num in numbers:
        if(num%5==0):
            print(num)
            
numbers=[10,2,25,67,92,100]
division(numbers)

Given Numbers is: [10, 2, 25, 67, 92, 100]
Divisible of 5 in numbers
10
25
100


# 14

In [1]:
def solve(s,t):
    cout = 0
    for i in range(0,len(s)-len(t)+1):
        if s[i:i + len(t)] == t:
            cout = cout + 1
    return cout

s = 'sdbsbHisnjHiKGKGKGKNBmvHijafdvcvFJGFJHi'
t = "Hi"
print(solve(s,t))

4


# 15

In [2]:
rows=6
for i in range(rows):
    for j in range(i):
        print(i,end='')
    print('')


1
22
333
4444
55555


# Lists

In [3]:
#1
def swap(lists):
    size = len(lists)
    
    temp = lists[0]
    lists[0] = lists[size - 1]
    lists[size - 1] = temp
    
    return lists
lists = [10,12,28,7,78,65]
print(swap(lists))

[65, 12, 28, 7, 78, 10]


In [5]:
#2
def swaps(List,n1,n2):
    List[n1], List[n2] = List[n2], List[n1]
    return List

List = [23,12,98,34,67,11]
n1, n2 = 2, 5
print(swaps(List,n1-1, n2-1))

[23, 67, 98, 34, 12, 11]


In [56]:
#3
#method1:
list1=[12,24,48,54,76,98]
print("The length of list is:",len(list1))
#method2:
list2=[34,23,5,66,80]
count = 0

for i in list2:
    count = count + 1
print("The Length of List:",count)

The length of list is: 6
The Length of List: 5


In [72]:
#4
#max
a=int(input("enter num"))
b=int(input("enter num"))
def maximum(a,b):
   
    if a>b:
        print(a)
    else:
        print(b)
maximum(a,b)

enter num45
enter num23
45


In [73]:
#5
#min
a=int(input("enter num"))
b=int(input("enter num"))
def minimum(a,b):
   
    if a<b:
        print(a)
    else:
        print(b)
minimum(a,b)

enter num34
enter num67
34


# Tuples

In [75]:
#1
tuple1=("Study",12,"char",12.67)
print("Size of Tuple1:",tuple1.__sizeof__(),"bytes")

Size of Tuple1: 56 bytes


In [76]:
#3
tup1 = (10,25,30,25,10)
print("The Original Tuple is:" + str(tup1))
res = sum(list(tup1))
print("sum of Tuples:" + str(res))

The Original Tuple is:(10, 25, 30, 25, 10)
sum of Tuples:100


In [90]:
#2
my_tup = (10,25,30,25,12,58,76)
k=2
coll = sorted(list(my_tup))
vals = []
for i in range(k):
    vals.append(coll[i])
    
for i in range((len(coll) - k), len(coll)):
    vals.append(coll[i])
print("Tuple:", str(my_tup))
print("K max & min:", str(vals))

Tuple: (10, 25, 30, 25, 12, 58, 76)
K max & min: [10, 12, 58, 76]


# String

In [97]:
#1
string = 'vidhun siddharth s'
half = int(len(string) / 2)

if len(string)%2==0:
    str1=string[:half]
    str2=string[half:]
else:
    str1 = string[:half]
    str2 = string[half+1:]
    
if str1 == str2:
    print(string, 'String is Palindrome')
else:
    print(string, 'string is symmetrical')
  

vidhun siddharth s string is symmetrical


In [98]:
#2
#reverse words
string = "tkeljtrj  ;eojrt ertjjt"

s=string.split()[::-1]
l = []
for i in s:
    l.append(i)
print(" ".join(l))

ertjjt ;eojrt tkeljtrj


# Set 

In [100]:
#1
set1={"Study",12,"char",12.67}
print("Size of set1:",set1.__sizeof__(),"bytes")

Size of set1: 200 bytes


In [109]:
#2
#method1
set_1={'t','y','u','i','o','a','e'}

for val in set_1:
    print(val, end='\n')
    

#method2
set_2=list({'t','y','u','i','o','a','e'})

for value in range(1,len(set_2)):
    print(set_2[value-1:value],end='')
print(set_2[-1:])

u
o
y
t
a
i
e
['u']['o']['y']['t']['a']['i']['e']


In [121]:
#3
#max and min in set
a={12,34,56,45,65,78}
print("The max element is:", max(a))
print("The Min element is", min(a))

The max element is: 78
The Min element is 12


# Dictionary

In [124]:
def dictt():
    key={}
    key[2] = 56
    key[1] = 2
    key[5] = 12
    key[3] = 10
    key[4] = 25
    print("Key_value",key)
    
    for i in sorted(key.keys()):
        print(i,end=" ")
    
def main():
    dictt()
    
if __name__ == "__main__":
    main()

Key_value {2: 56, 1: 2, 5: 12, 3: 10, 4: 25}
1 2 3 4 5 

In [126]:
dic={}

a,b,c=5,3,10
p,q,r=12,6,4

dic["x-y+z"] = [a-b+c,p-q+r]

print(dic)

{'x-y+z': [12, 10]}


# Matrix

In [138]:
#2
#Adding Matrix
import numpy as np
m1 = np.array([[1,3,4], [1,3,4]])
m2 = np.array([[6,4,2], [2,4,6]])

print("Add Matrix")
a = np.add(m1, m2)
print(a)
print('\n')

print("Sub Matrix")
b = np.subtract(m1, m2)
print(b)


Add Matrix
[[ 7  7  6]
 [ 3  7 10]]


Sub Matrix
[[-5 -1  2]
 [-1 -1 -2]]


# Function

In [140]:
#1
def func(a, b):
    return a+b

import inspect

print(inspect.signature(func))

(a, b)


In [144]:
#2
def good(name, num):
    print("Hello From %s , %s" % (name, num))
    
good("Sharukh", 18)

Hello From Sharukh , 18
